"""table_appointment_details_added

Revision ID: a9f899af20ff
Revises: 74f169b0890c
Create Date: 2019-10-24 17:58:13.872568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f899af20ff'
down_revision = '74f169b0890c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('patient_approval', sa.Boolean(), nullable=True),
    sa.Column('doctor_approval', sa.Boolean(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_detail')
    # ### end Alembic commands ###
